[2024-09-29T02:57:23.683+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T02:57:23.694+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:55:21.359736+00:00 [queued]>
[2024-09-29T02:57:23.699+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:55:21.359736+00:00 [queued]>
[2024-09-29T02:57:23.699+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T02:57:23.707+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_LoadS3> on 2024-09-29 02:55:21.359736+00:00
[2024-09-29T02:57:23.710+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T02:57:23.711+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2024-09-29T02:57:23.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'validate_LoadS3', 'manual__2024-09-29T02:55:21.359736+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp44071yq7']
[2024-09-29T02:57:23.712+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask validate_LoadS3
[2024-09-29T02:57:23.734+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:55:21.359736+00:00 [running]> on host 2e7d9707a826
[2024-09-29T02:57:23.777+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='validate_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T02:55:21.359736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T02:55:21.359736+00:00'
[2024-09-29T02:57:23.778+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T02:57:23.784+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:57:23.785+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/dataValidate.py']
[2024-09-29T02:57:23.789+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:57:25.047+0000] {subprocess.py:93} INFO - data from S3 extracted
[2024-09-29T02:57:25.048+0000] {subprocess.py:93} INFO - Data transformed
[2024-09-29T02:57:25.049+0000] {subprocess.py:93} INFO - Data saved to S3
[2024-09-29T02:57:25.161+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T02:57:25.161+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T02:57:25.175+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=validate_LoadS3, execution_date=20240929T025521, start_date=20240929T025723, end_date=20240929T025725
[2024-09-29T02:57:25.186+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T02:57:25.199+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-29T02:57:25.200+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
