[2024-09-25T19:39:56.793+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:39:56.803+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:37:54.243556+00:00 [queued]>
[2024-09-25T19:39:56.807+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:37:54.243556+00:00 [queued]>
[2024-09-25T19:39:56.807+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-25T19:39:56.813+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 19:37:54.243556+00:00
[2024-09-25T19:39:56.815+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:39:56.816+0000] {standard_task_runner.py:63} INFO - Started process 107 to run task
[2024-09-25T19:39:56.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T19:37:54.243556+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpok_1dfwz']
[2024-09-25T19:39:56.818+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask scrape
[2024-09-25T19:39:56.841+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:37:54.243556+00:00 [running]> on host a5905166bf2e
[2024-09-25T19:39:56.876+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T19:37:54.243556+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T19:37:54.243556+00:00'
[2024-09-25T19:39:56.877+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:39:56.883+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:39:56.884+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T19:39:56.887+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:39:57.331+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-25T19:39:57.331+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 7, in <module>
[2024-09-25T19:39:57.331+0000] {subprocess.py:93} INFO -     from pipelineActions import *
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 9, in <module>
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -     access = config.get('aws_boto_credentials', 'access_key')
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 759, in get
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -     d = self._unify_values(section, vars)
[2024-09-25T19:39:57.332+0000] {subprocess.py:93} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-25T19:39:57.333+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 1130, in _unify_values
[2024-09-25T19:39:57.333+0000] {subprocess.py:93} INFO -     raise NoSectionError(section) from None
[2024-09-25T19:39:57.333+0000] {subprocess.py:93} INFO - configparser.NoSectionError: No section: 'aws_boto_credentials'
[2024-09-25T19:39:57.359+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-25T19:39:57.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:39:57.365+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T19:39:57.368+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T193754, start_date=20240925T193956, end_date=20240925T193957
[2024-09-25T19:39:57.374+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task scrape (Bash command failed. The command returned a non-zero exit code 1.; 107)
[2024-09-25T19:39:57.407+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:39:57.417+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:39:57.418+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
