[2024-09-25T19:25:02.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:25:02.065+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:23:00.570395+00:00 [queued]>
[2024-09-25T19:25:02.069+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:23:00.570395+00:00 [queued]>
[2024-09-25T19:25:02.069+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-25T19:25:02.075+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 19:23:00.570395+00:00
[2024-09-25T19:25:02.079+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:25:02.080+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-09-25T19:25:02.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T19:23:00.570395+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpwvq1iy30']
[2024-09-25T19:25:02.082+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask scrape
[2024-09-25T19:25:02.107+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:23:00.570395+00:00 [running]> on host 8445e15c9faf
[2024-09-25T19:25:02.145+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T19:23:00.570395+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T19:23:00.570395+00:00'
[2024-09-25T19:25:02.145+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:25:02.152+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:25:02.153+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../tasks/testcode.py']
[2024-09-25T19:25:02.157+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:25:02.176+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmp_rsfnser/../tasks/testcode.py': [Errno 2] No such file or directory
[2024-09-25T19:25:02.178+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T19:25:02.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:25:02.185+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T19:25:02.187+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T192300, start_date=20240925T192502, end_date=20240925T192502
[2024-09-25T19:25:02.194+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 129)
[2024-09-25T19:25:02.219+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:25:02.229+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:25:02.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
