[2024-09-25T18:37:32.918+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T18:37:32.931+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T18:32:02.624431+00:00 [queued]>
[2024-09-25T18:37:32.936+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T18:32:02.624431+00:00 [queued]>
[2024-09-25T18:37:32.936+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-09-25T18:37:32.943+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 18:32:02.624431+00:00
[2024-09-25T18:37:32.945+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=702) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T18:37:32.946+0000] {standard_task_runner.py:63} INFO - Started process 703 to run task
[2024-09-25T18:37:32.947+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T18:32:02.624431+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpct6ybfp1']
[2024-09-25T18:37:32.949+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask scrape
[2024-09-25T18:37:32.970+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T18:32:02.624431+00:00 [running]> on host 233e233591d2
[2024-09-25T18:37:33.009+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T18:32:02.624431+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T18:32:02.624431+00:00'
[2024-09-25T18:37:33.010+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T18:37:33.016+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T18:37:33.017+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../tasks/testcode.py']
[2024-09-25T18:37:33.021+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T18:37:33.039+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmp53vf1vi2/../tasks/testcode.py': [Errno 2] No such file or directory
[2024-09-25T18:37:33.041+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T18:37:33.041+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T18:37:33.047+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T18:37:33.050+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T183202, start_date=20240925T183732, end_date=20240925T183733
[2024-09-25T18:37:33.055+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 703)
[2024-09-25T18:37:33.085+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T18:37:33.093+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T18:37:33.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
