[2024-09-25T21:06:14.638+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T21:06:14.666+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [queued]>
[2024-09-25T21:06:14.678+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [queued]>
[2024-09-25T21:06:14.678+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T21:06:14.692+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-25 21:06:14.004529+00:00
[2024-09-25T21:06:14.697+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T21:06:14.699+0000] {standard_task_runner.py:63} INFO - Started process 1263 to run task
[2024-09-25T21:06:14.699+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'manual__2024-09-25T21:06:14.004529+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpdudwkyjc']
[2024-09-25T21:06:14.705+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask scrape_LoadS3
[2024-09-25T21:06:14.760+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [running]> on host a5905166bf2e
[2024-09-25T21:06:14.844+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T21:06:14.004529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T21:06:14.004529+00:00'
[2024-09-25T21:06:14.845+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T21:06:14.865+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T21:06:14.866+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /***/tasks/flightDataWebScrape.py']
[2024-09-25T21:06:14.876+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T21:06:14.920+0000] {subprocess.py:93} INFO - python3: can't open file '/***/tasks/flightDataWebScrape.py': [Errno 2] No such file or directory
[2024-09-25T21:06:14.924+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T21:06:14.925+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T21:06:14.936+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T21:06:14.941+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240925T210614, start_date=20240925T210614, end_date=20240925T210614
[2024-09-25T21:06:14.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 2.; 1263)
[2024-09-25T21:06:14.966+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T21:06:14.980+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T21:06:14.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
