[2024-09-25T21:08:16.069+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T21:08:16.097+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [queued]>
[2024-09-25T21:08:16.104+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [queued]>
[2024-09-25T21:08:16.105+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-25T21:08:16.117+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-25 21:06:14.004529+00:00
[2024-09-25T21:08:16.123+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T21:08:16.126+0000] {standard_task_runner.py:63} INFO - Started process 1299 to run task
[2024-09-25T21:08:16.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'manual__2024-09-25T21:06:14.004529+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpefqqqz20']
[2024-09-25T21:08:16.127+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask scrape_LoadS3
[2024-09-25T21:08:16.167+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-25T21:06:14.004529+00:00 [running]> on host a5905166bf2e
[2024-09-25T21:08:16.211+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T21:06:14.004529+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T21:06:14.004529+00:00'
[2024-09-25T21:08:16.212+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T21:08:16.221+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T21:08:16.222+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /***/tasks/flightDataWebScrape.py']
[2024-09-25T21:08:16.226+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T21:08:16.277+0000] {subprocess.py:93} INFO - python3: can't open file '/***/tasks/flightDataWebScrape.py': [Errno 2] No such file or directory
[2024-09-25T21:08:16.278+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T21:08:16.279+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T21:08:16.288+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T21:08:16.294+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240925T210614, start_date=20240925T210816, end_date=20240925T210816
[2024-09-25T21:08:16.302+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 2.; 1299)
[2024-09-25T21:08:16.310+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T21:08:16.327+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T21:08:16.332+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
