[2024-09-25T17:51:50.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T17:51:50.173+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T17:49:47.491079+00:00 [queued]>
[2024-09-25T17:51:50.178+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T17:49:47.491079+00:00 [queued]>
[2024-09-25T17:51:50.178+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-25T17:51:50.186+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 17:49:47.491079+00:00
[2024-09-25T17:51:50.189+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T17:51:50.190+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2024-09-25T17:51:50.190+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T17:49:47.491079+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpewkzf_p0']
[2024-09-25T17:51:50.191+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask scrape
[2024-09-25T17:51:50.214+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T17:49:47.491079+00:00 [running]> on host 233e233591d2
[2024-09-25T17:51:50.255+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T17:49:47.491079+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T17:49:47.491079+00:00'
[2024-09-25T17:51:50.256+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T17:51:50.264+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T17:51:50.264+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../testcode.py']
[2024-09-25T17:51:50.268+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T17:51:50.287+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpk70ll8ct/../testcode.py': [Errno 2] No such file or directory
[2024-09-25T17:51:50.289+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T17:51:50.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T17:51:50.294+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T17:51:50.298+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T174947, start_date=20240925T175150, end_date=20240925T175150
[2024-09-25T17:51:50.304+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 96)
[2024-09-25T17:51:50.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T17:51:50.338+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T17:51:50.339+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
