[2024-09-25T19:14:51.650+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:14:51.660+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:14:50.791863+00:00 [queued]>
[2024-09-25T19:14:51.663+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:14:50.791863+00:00 [queued]>
[2024-09-25T19:14:51.664+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:14:51.669+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 19:14:50.791863+00:00
[2024-09-25T19:14:51.672+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1223) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:14:51.673+0000] {standard_task_runner.py:63} INFO - Started process 1224 to run task
[2024-09-25T19:14:51.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T19:14:50.791863+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp3r6n0qvk']
[2024-09-25T19:14:51.676+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask scrape
[2024-09-25T19:14:51.700+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:14:50.791863+00:00 [running]> on host 233e233591d2
[2024-09-25T19:14:51.742+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T19:14:50.791863+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T19:14:50.791863+00:00'
[2024-09-25T19:14:51.742+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:14:51.749+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:14:51.749+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python tasks/testcode.py']
[2024-09-25T19:14:51.754+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:14:51.772+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpcs2qgwzj/tasks/testcode.py': [Errno 2] No such file or directory
[2024-09-25T19:14:51.773+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T19:14:51.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:14:51.780+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T19:14:51.782+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T191450, start_date=20240925T191451, end_date=20240925T191451
[2024-09-25T19:14:51.791+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 1224)
[2024-09-25T19:14:51.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:14:51.821+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:14:51.822+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
