[2024-09-29T02:36:11.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T02:36:11.548+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T02:36:11.070635+00:00 [queued]>
[2024-09-29T02:36:11.553+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T02:36:11.070635+00:00 [queued]>
[2024-09-29T02:36:11.553+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T02:36:11.561+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-29 02:36:11.070635+00:00
[2024-09-29T02:36:11.564+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=462) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T02:36:11.565+0000] {standard_task_runner.py:63} INFO - Started process 463 to run task
[2024-09-29T02:36:11.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'manual__2024-09-29T02:36:11.070635+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpxmpyfynz']
[2024-09-29T02:36:11.567+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask scrape_LoadS3
[2024-09-29T02:36:11.592+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T02:36:11.070635+00:00 [running]> on host 7b437d7ff517
[2024-09-29T02:36:11.639+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T02:36:11.070635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T02:36:11.070635+00:00'
[2024-09-29T02:36:11.640+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T02:36:11.647+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:36:11.647+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-29T02:36:11.652+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:36:12.411+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-29T02:36:12.411+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 86, in <module>
[2024-09-29T02:36:12.411+0000] {subprocess.py:93} INFO -     main()
[2024-09-29T02:36:12.412+0000] {subprocess.py:93} INFO -     ^^^^^^
[2024-09-29T02:36:12.412+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 22, in main
[2024-09-29T02:36:12.412+0000] {subprocess.py:93} INFO -     print(year + " fetched")
[2024-09-29T02:36:12.412+0000] {subprocess.py:93} INFO -           ~~~~~^~~~~~~~~~~~
[2024-09-29T02:36:12.412+0000] {subprocess.py:93} INFO - TypeError: unsupported operand type(s) for +: 'int' and 'str'
[2024-09-29T02:36:12.443+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-29T02:36:12.443+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T02:36:12.451+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-29T02:36:12.456+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240929T023611, start_date=20240929T023611, end_date=20240929T023612
[2024-09-29T02:36:12.465+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 463)
[2024-09-29T02:36:12.487+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T02:36:12.499+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T02:36:12.500+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
