[2024-09-25T21:35:02.311+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T21:35:02.323+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T21:35:02.331+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T21:35:02.334+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-25T21:35:02.366+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-24 00:00:00+00:00
[2024-09-25T21:35:02.386+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9v64kwgy']
[2024-09-25T21:35:02.391+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask scrape_LoadS3
[2024-09-25T21:35:02.420+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-25T21:35:02.425+0000] {standard_task_runner.py:72} INFO - Started process 283 to run task
[2024-09-25T21:35:02.527+0000] {task_command.py:467} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host fa5d07744004
[2024-09-25T21:35:02.631+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-25T21:35:02.633+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T21:35:02.666+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T21:35:02.667+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T21:35:02.690+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T21:35:02.741+0000] {subprocess.py:93} INFO - python3: can't open file '/tmp/***tmpmfdvkdou/opt/***/tasks/flightDataWebScrape.py': [Errno 2] No such file or directory
[2024-09-25T21:35:02.751+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T21:35:02.767+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T21:35:02.773+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240925T213502, end_date=20240925T213502
[2024-09-25T21:35:02.787+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T21:35:02.789+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 2.; 283)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T21:35:02.826+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-25T21:35:02.851+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T21:35:02.855+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-25T21:41:03.347+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T21:41:03.360+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T21:41:03.366+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T21:41:03.367+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-25T21:41:03.375+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-24 00:00:00+00:00
[2024-09-25T21:41:03.381+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp4x_1_7yu']
[2024-09-25T21:41:03.385+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask scrape_LoadS3
[2024-09-25T21:41:03.387+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-25T21:41:03.387+0000] {standard_task_runner.py:72} INFO - Started process 482 to run task
[2024-09-25T21:41:03.414+0000] {task_command.py:467} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host fa5d07744004
[2024-09-25T21:41:03.452+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-25T21:41:03.453+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T21:41:03.461+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T21:41:03.462+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T21:41:03.468+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T21:41:03.981+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-25T21:41:03.981+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 6, in <module>
[2024-09-25T21:41:03.981+0000] {subprocess.py:93} INFO -     from pipelineActions import *
[2024-09-25T21:41:03.982+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 9, in <module>
[2024-09-25T21:41:03.983+0000] {subprocess.py:93} INFO -     script_path = pathlib.Path(__file__).parent.resolve()
[2024-09-25T21:41:03.983+0000] {subprocess.py:93} INFO -                   ^^^^^^^
[2024-09-25T21:41:03.985+0000] {subprocess.py:93} INFO - NameError: name 'pathlib' is not defined. Did you forget to import 'pathlib'?
[2024-09-25T21:41:04.013+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-25T21:41:04.024+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T21:41:04.028+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240925T214103, end_date=20240925T214104
[2024-09-25T21:41:04.035+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T21:41:04.035+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 482)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T21:41:04.063+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-25T21:41:04.070+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T21:41:04.071+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T02:11:25.235+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [skipped]> on host 7b437d7ff517
[2024-09-29T02:11:25.414+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-29T02:11:25.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T02:11:25.440+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:11:25.441+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-29T02:11:25.458+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:11:26.438+0000] {subprocess.py:93} INFO - Error scraping source web
[2024-09-29T02:11:26.500+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T02:11:26.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T02:11:26.516+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240924T000000, start_date=20240929T021124, end_date=20240929T021126
[2024-09-30T03:11:41.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-30T03:11:41.205+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-30T03:11:41.217+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-30T03:11:41.218+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-30T03:11:41.230+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-24 00:00:00+00:00
[2024-09-30T03:11:41.236+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T03:11:41.242+0000] {standard_task_runner.py:63} INFO - Started process 147 to run task
[2024-09-30T03:11:41.238+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp59ed3w8w']
[2024-09-30T03:11:41.245+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask scrape_LoadS3
[2024-09-30T03:11:41.306+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host 60abf2d32f6d
[2024-09-30T03:11:41.411+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-30T03:11:41.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-30T03:11:41.425+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-30T03:11:41.426+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-30T03:11:41.442+0000] {subprocess.py:86} INFO - Output:
[2024-09-30T03:11:42.418+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-30T03:11:42.418+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 5, in <module>
[2024-09-30T03:11:42.418+0000] {subprocess.py:93} INFO -     from pipelineActions import *
[2024-09-30T03:11:42.419+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 13, in <module>
[2024-09-30T03:11:42.424+0000] {subprocess.py:93} INFO -     config.read(config_file_path)
[2024-09-30T03:11:42.424+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 684, in read
[2024-09-30T03:11:42.424+0000] {subprocess.py:93} INFO -     self._read(fp, filename)
[2024-09-30T03:11:42.424+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 1063, in _read
[2024-09-30T03:11:42.424+0000] {subprocess.py:93} INFO -     raise MissingSectionHeaderError(fpname, lineno, line)
[2024-09-30T03:11:42.425+0000] {subprocess.py:93} INFO - configparser.MissingSectionHeaderError: File contains no section headers.
[2024-09-30T03:11:42.425+0000] {subprocess.py:93} INFO - file: PosixPath('/opt/***/tasks/pipeline.conf'), line: 1
[2024-09-30T03:11:42.425+0000] {subprocess.py:93} INFO - 'bucket_name = "flightcrashbucket"\n'
[2024-09-30T03:11:42.473+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-30T03:11:42.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-30T03:11:42.487+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-30T03:11:42.490+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240924T000000, start_date=20240930T031141, end_date=20240930T031142
[2024-09-30T03:11:42.499+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 147)
[2024-09-30T03:11:42.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-30T03:11:42.534+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T03:11:42.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T02:13:45.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T02:13:45.438+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-10-02T02:13:45.456+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-10-02T02:13:45.457+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-10-02T02:13:45.473+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-24 00:00:00+00:00
[2024-10-02T02:13:45.487+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T02:13:45.489+0000] {standard_task_runner.py:63} INFO - Started process 168 to run task
[2024-10-02T02:13:45.483+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpkvfb21qp']
[2024-10-02T02:13:45.497+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask scrape_LoadS3
[2024-10-02T02:13:45.565+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-24T00:00:00+00:00 [running]> on host ac8ffcfe4778
[2024-10-02T02:13:45.677+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-10-02T02:13:45.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T02:13:45.704+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-02T02:13:45.709+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-10-02T02:13:45.724+0000] {subprocess.py:86} INFO - Output:
[2024-10-02T02:15:01.502+0000] {subprocess.py:93} INFO - HTTPSConnectionPool(host='www.planecrashinfo.com', port=443): Max retries exceeded with url: /1920/1920.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa7b784d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-10-02T02:15:01.537+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-02T02:15:01.538+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T02:15:01.544+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-02T02:15:01.547+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240924T000000, start_date=20241002T021345, end_date=20241002T021501
[2024-10-02T02:15:01.564+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 168)
[2024-10-02T02:15:01.580+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T02:15:01.591+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T02:15:01.592+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
