[2024-09-30T03:11:41.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-30T03:11:41.075+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-30T03:11:41.085+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-30T03:11:41.089+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-30T03:11:41.106+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-27 00:00:00+00:00
[2024-09-30T03:11:41.112+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T03:11:41.116+0000] {standard_task_runner.py:63} INFO - Started process 145 to run task
[2024-09-30T03:11:41.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-27T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9fxpshzu']
[2024-09-30T03:11:41.127+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask scrape_LoadS3
[2024-09-30T03:11:41.175+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [running]> on host 60abf2d32f6d
[2024-09-30T03:11:41.247+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-27T00:00:00+00:00'
[2024-09-30T03:11:41.248+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-30T03:11:41.261+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-30T03:11:41.262+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-30T03:11:41.270+0000] {subprocess.py:86} INFO - Output:
[2024-09-30T03:11:42.431+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-30T03:11:42.431+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 5, in <module>
[2024-09-30T03:11:42.433+0000] {subprocess.py:93} INFO -     from pipelineActions import *
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 13, in <module>
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -     config.read(config_file_path)
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 684, in read
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -     self._read(fp, filename)
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 1063, in _read
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO -     raise MissingSectionHeaderError(fpname, lineno, line)
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO - configparser.MissingSectionHeaderError: File contains no section headers.
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO - file: PosixPath('/opt/***/tasks/pipeline.conf'), line: 1
[2024-09-30T03:11:42.434+0000] {subprocess.py:93} INFO - 'bucket_name = "flightcrashbucket"\n'
[2024-09-30T03:11:42.490+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-30T03:11:42.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-30T03:11:42.497+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-30T03:11:42.501+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240927T000000, start_date=20240930T031141, end_date=20240930T031142
[2024-09-30T03:11:42.513+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 145)
[2024-09-30T03:11:42.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-30T03:11:42.563+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T03:11:42.565+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T02:13:45.452+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T02:13:45.486+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-10-02T02:13:45.497+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-10-02T02:13:45.498+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-10-02T02:13:45.519+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-27 00:00:00+00:00
[2024-10-02T02:13:45.523+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=160) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T02:13:45.525+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2024-10-02T02:13:45.526+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'scheduled__2024-09-27T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9livq62h']
[2024-10-02T02:13:45.529+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask scrape_LoadS3
[2024-10-02T02:13:45.592+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 scheduled__2024-09-27T00:00:00+00:00 [running]> on host ac8ffcfe4778
[2024-10-02T02:13:45.729+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-27T00:00:00+00:00'
[2024-10-02T02:13:45.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T02:13:45.748+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-02T02:13:45.748+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-10-02T02:13:45.758+0000] {subprocess.py:86} INFO - Output:
[2024-10-02T02:15:01.884+0000] {subprocess.py:93} INFO - HTTPSConnectionPool(host='www.planecrashinfo.com', port=443): Max retries exceeded with url: /1920/1920.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8b1f1400>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-10-02T02:15:01.917+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-02T02:15:01.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T02:15:01.926+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-02T02:15:01.930+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240927T000000, start_date=20241002T021345, end_date=20241002T021501
[2024-10-02T02:15:01.940+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task scrape_LoadS3 (Bash command failed. The command returned a non-zero exit code 1.; 170)
[2024-10-02T02:15:01.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T02:15:01.959+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T02:15:01.966+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
