[2024-09-25T20:09:59.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T20:09:59.524+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_loadS3 manual__2024-09-25T20:07:57.412500+00:00 [queued]>
[2024-09-25T20:09:59.528+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_loadS3 manual__2024-09-25T20:07:57.412500+00:00 [queued]>
[2024-09-25T20:09:59.528+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-09-25T20:09:59.533+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_loadS3> on 2024-09-25 20:07:57.412500+00:00
[2024-09-25T20:09:59.536+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=514) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T20:09:59.537+0000] {standard_task_runner.py:63} INFO - Started process 515 to run task
[2024-09-25T20:09:59.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_loadS3', 'manual__2024-09-25T20:07:57.412500+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpfnc5dkiu']
[2024-09-25T20:09:59.538+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask scrape_loadS3
[2024-09-25T20:09:59.563+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_loadS3 manual__2024-09-25T20:07:57.412500+00:00 [running]> on host a5905166bf2e
[2024-09-25T20:09:59.599+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_loadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T20:07:57.412500+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T20:07:57.412500+00:00'
[2024-09-25T20:09:59.599+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T20:09:59.605+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T20:09:59.606+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T20:09:59.610+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T20:10:00.138+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-25T20:10:00.138+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 89, in <module>
[2024-09-25T20:10:00.138+0000] {subprocess.py:93} INFO -     saveToS3([1,2,3], 'bronze1.csv')
[2024-09-25T20:10:00.138+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 51, in saveToS3
[2024-09-25T20:10:00.139+0000] {subprocess.py:93} INFO -     fieldnames = data[0].keys()
[2024-09-25T20:10:00.139+0000] {subprocess.py:93} INFO -                  ^^^^^^^^^^^^
[2024-09-25T20:10:00.139+0000] {subprocess.py:93} INFO - AttributeError: 'int' object has no attribute 'keys'
[2024-09-25T20:10:00.188+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-25T20:10:00.189+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T20:10:00.194+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T20:10:00.199+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_loadS3, execution_date=20240925T200757, start_date=20240925T200959, end_date=20240925T201000
[2024-09-25T20:10:00.205+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task scrape_loadS3 (Bash command failed. The command returned a non-zero exit code 1.; 515)
[2024-09-25T20:10:00.211+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T20:10:00.224+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T20:10:00.226+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
