[2024-09-29T03:50:50.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T03:50:51.009+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T03:50:50.051053+00:00 [queued]>
[2024-09-29T03:50:51.014+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T03:50:50.051053+00:00 [queued]>
[2024-09-29T03:50:51.014+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T03:50:51.023+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape_LoadS3> on 2024-09-29 03:50:50.051053+00:00
[2024-09-29T03:50:51.026+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=916) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T03:50:51.027+0000] {standard_task_runner.py:63} INFO - Started process 917 to run task
[2024-09-29T03:50:51.028+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape_LoadS3', 'manual__2024-09-29T03:50:50.051053+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1j_0mtn_']
[2024-09-29T03:50:51.029+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask scrape_LoadS3
[2024-09-29T03:50:51.052+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape_LoadS3 manual__2024-09-29T03:50:50.051053+00:00 [running]> on host 2e7d9707a826
[2024-09-29T03:50:51.101+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T03:50:50.051053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T03:50:50.051053+00:00'
[2024-09-29T03:50:51.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T03:50:51.108+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T03:50:51.109+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-29T03:50:51.114+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T03:52:31.757+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-09-29T03:52:31.758+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-29T03:52:31.760+0000] {process_utils.py:132} INFO - Sending 15 to group 917. PIDs of all processes in the group: [918, 917]
[2024-09-29T03:52:31.761+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 917
[2024-09-29T03:52:31.761+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-29T03:52:31.762+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-09-29T03:52:31.762+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T03:52:31.773+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-29T03:52:31.780+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape_LoadS3, execution_date=20240929T035050, start_date=20240929T035051, end_date=20240929T035231
[2024-09-29T03:52:31.792+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=918, status='terminated', started='03:50:50') (918) terminated with exit code None
[2024-09-29T03:52:31.792+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=917, status='terminated', exitcode=2, started='03:50:50') (917) terminated with exit code 2
