[2024-09-29T02:53:54.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T02:53:54.504+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:52:18.692048+00:00 [queued]>
[2024-09-29T02:53:54.508+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:52:18.692048+00:00 [queued]>
[2024-09-29T02:53:54.509+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T02:53:54.516+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_LoadS3> on 2024-09-29 02:52:18.692048+00:00
[2024-09-29T02:53:54.521+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T02:53:54.523+0000] {standard_task_runner.py:63} INFO - Started process 149 to run task
[2024-09-29T02:53:54.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'validate_LoadS3', 'manual__2024-09-29T02:52:18.692048+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp68mm_d8b']
[2024-09-29T02:53:54.525+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask validate_LoadS3
[2024-09-29T02:53:54.552+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T02:52:18.692048+00:00 [running]> on host 2e7d9707a826
[2024-09-29T02:53:54.599+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='validate_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T02:52:18.692048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T02:52:18.692048+00:00'
[2024-09-29T02:53:54.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T02:53:54.607+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:53:54.608+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/dataValidate.py']
[2024-09-29T02:53:54.614+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:53:57.114+0000] {subprocess.py:93} INFO - data from S3 extracted
[2024-09-29T02:53:57.114+0000] {subprocess.py:93} INFO - Data transformed
[2024-09-29T02:53:57.115+0000] {subprocess.py:93} INFO - Data saved to S3
[2024-09-29T02:53:57.240+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T02:53:57.241+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T02:53:57.255+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=validate_LoadS3, execution_date=20240929T025218, start_date=20240929T025354, end_date=20240929T025357
[2024-09-29T02:53:57.284+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T02:53:57.295+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-29T02:53:57.296+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
