[2024-09-29T03:20:00.240+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T03:20:00.253+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T03:18:00.637923+00:00 [queued]>
[2024-09-29T03:20:00.257+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T03:18:00.637923+00:00 [queued]>
[2024-09-29T03:20:00.257+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T03:20:00.266+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_LoadS3> on 2024-09-29 03:18:00.637923+00:00
[2024-09-29T03:20:00.269+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T03:20:00.270+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2024-09-29T03:20:00.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'validate_LoadS3', 'manual__2024-09-29T03:18:00.637923+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpt_dzn8u_']
[2024-09-29T03:20:00.272+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask validate_LoadS3
[2024-09-29T03:20:00.295+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.validate_LoadS3 manual__2024-09-29T03:18:00.637923+00:00 [running]> on host 2e7d9707a826
[2024-09-29T03:20:00.334+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='validate_LoadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T03:18:00.637923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T03:18:00.637923+00:00'
[2024-09-29T03:20:00.334+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T03:20:00.341+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T03:20:00.342+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/dataValidate.py']
[2024-09-29T03:20:00.347+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T03:20:01.772+0000] {subprocess.py:93} INFO - data from S3 extracted
[2024-09-29T03:20:01.774+0000] {subprocess.py:93} INFO - Data transformed
[2024-09-29T03:20:01.774+0000] {subprocess.py:93} INFO - Data saved to S3
[2024-09-29T03:20:01.901+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T03:20:01.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T03:20:01.915+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=validate_LoadS3, execution_date=20240929T031800, start_date=20240929T032000, end_date=20240929T032001
[2024-09-29T03:20:01.956+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T03:20:01.967+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:20:01.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
