[2024-09-25T20:11:22.567+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T20:11:22.577+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_loadS3 manual__2024-09-25T20:11:19.494625+00:00 [queued]>
[2024-09-25T20:11:22.581+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.validate_loadS3 manual__2024-09-25T20:11:19.494625+00:00 [queued]>
[2024-09-25T20:11:22.581+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T20:11:22.587+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_loadS3> on 2024-09-25 20:11:19.494625+00:00
[2024-09-25T20:11:22.589+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=539) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T20:11:22.590+0000] {standard_task_runner.py:63} INFO - Started process 540 to run task
[2024-09-25T20:11:22.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'validate_loadS3', 'manual__2024-09-25T20:11:19.494625+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmps42czmos']
[2024-09-25T20:11:22.592+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask validate_loadS3
[2024-09-25T20:11:22.615+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.validate_loadS3 manual__2024-09-25T20:11:19.494625+00:00 [running]> on host a5905166bf2e
[2024-09-25T20:11:22.650+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='validate_loadS3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T20:11:19.494625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T20:11:19.494625+00:00'
[2024-09-25T20:11:22.651+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T20:11:22.657+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T20:11:22.657+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T20:11:22.662+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T20:11:24.076+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-25T20:11:24.076+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T20:11:24.089+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=validate_loadS3, execution_date=20240925T201119, start_date=20240925T201122, end_date=20240925T201124
[2024-09-25T20:11:24.124+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-25T20:11:24.136+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-25T20:11:24.137+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
